name: Count Python Lines of Code

# on: [push]
on: 
  workflow_dispatch:

jobs:
  count-python-lines:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Count lines of Python code
      run: |
        echo "Counting lines of Python code..."
        find . -name '*.py' | xargs wc -l | sed -E "s/^[^0-9]*([0-9]+) (.*)$/\2: \1 lines/"
